### ISSUE TITLE
set_correction() Doesn't appear to work

### ISSUE THREAD

**Issue by pwarren** [etherkit/Si5351Arduino#7]
From the 'jason' branch, I run the calibration example, with a correction of 22, and my board output's 10MHz, to the limit of my counter (1Hz).

Then if I run, a simple sketch that sets the clock as per the calibration example, with no set_correction() call. get_correction() returns -1, and the output is 22 Hz above 10MHz

Am I doing it wrong, or not understanding how the set_correction() works?  Should I do set_correction(22); with each sketch I write?

**Comment by NT7S** [comment]
I believe that's probably a function of the EEPROM routines, which I have removed from the latest commit.

You should do a set_correction() for each sketch. I removed the EEPROM routines to make the code more portable, so that you can write your own calibration logic to read and set the cal constant into NV memory as appropriate for your device and use.
